import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Custom sidebar with logical organization
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Stahlwille 766 Integration App',
      collapsed: false,
      link: {type: 'doc', id: 'stahlwille-766/stahlwille-766-user-guide'},
      items: [
        'stahlwille-766/installation',
        'stahlwille-766/configuration',
        'stahlwille-766/applying-changes',
        'stahlwille-766/ui-widget',
        'stahlwille-766/data-layer',
        'stahlwille-766/outputcureves',
        'stahlwille-766/licensing',
        'stahlwille-766/troubleshooting',
        'stahlwille-766/quick-reference',
      ],
    },
    {
      type: 'category',
      label: 'Opex Solution',
      collapsed: true,
      items: [
        'opex/opex-overview',
      ],
    },
  ],
};

export default sidebars;
