import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Custom sidebar with logical organization
  tutorialSidebar: [
    {
      type: 'category',
      label: 'User Guide',
      collapsed: false,
      link: {type: 'doc', id: 'user-guide/user-guide-overview'},
      items: [
        'user-guide/installation',
        'user-guide/configuration',
        'user-guide/applying-changes',
        'user-guide/ui-widget',
        'user-guide/data-layer',
        'user-guide/licensing',
        'user-guide/troubleshooting',
        'user-guide/quick-reference',
      ],
    },
  ],
};

export default sidebars;
