import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * OGS Documentation sidebar — generated from mkdocs.yml nav tree.
 * This sidebar is used by the 'ogs' docs plugin instance.
 */
const sidebars: SidebarsConfig = {
  ogsSidebar: [
    {type: 'doc', id: 'index', label: 'Home'},
    {
      type: 'category',
      label: 'Tool configuration',
      collapsed: false,
      items: [
        {type: 'doc', id: 'tools/README', label: 'Overview'},
        {
          type: 'category',
          label: 'Remote Tool Gateway',
          items: [{type: 'doc', id: 'tools/remote-tool', label: 'Overview'}],
        },
        {
          type: 'category',
          label: 'OpenProtocol tools',
          items: [
            {type: 'autogenerated', dirName: 'tools/openprotocol'},
          ],
        },
        {
          type: 'category',
          label: 'Non-OpenProtocol tightening tools',
          items: [
            {type: 'autogenerated', dirName: 'tools/non-openprotocol'},
          ],
        },
        {
          type: 'category',
          label: 'Misc tools',
          items: [
            {type: 'autogenerated', dirName: 'tools/misc'},
          ],
        },
        {
          type: 'category',
          label: 'Camera systems',
          items: [
            {type: 'doc', id: 'tools/misc/keyence-iv4', label: 'Keyence IV4 AI Vision sensor'},
            {type: 'doc', id: 'tools/misc/hikrobot-vm', label: 'HikRobot VisionMaster'},
            {type: 'doc', id: 'tools/misc/wenglor-weqube', label: 'Wenglor weQube Smart camera'},
          ],
        },
        {
          type: 'category',
          label: 'Positioning',
          items: [
            {type: 'autogenerated', dirName: 'tools/positioning'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Additional configuration',
      items: [
        {type: 'doc', id: 'tools/misc/socket-tray', label: 'Socket trays'},
        {type: 'doc', id: 'tools/misc/projector', label: 'Projector'},
      ],
    },
    {
      type: 'category',
      label: 'Data output',
      items: [
        {type: 'autogenerated', dirName: 'dataoutput'},
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      items: [
        {type: 'doc', id: 'v3/getting-started', label: 'Getting Started'},
        {
          type: 'category',
          label: 'LUA interfaces',
          items: [
            {type: 'autogenerated', dirName: 'v3/lua'},
          ],
        },
        {type: 'doc', id: 'v3/lua/customtools', label: 'LUA custom tools'},
      ],
    },
    {
      type: 'category',
      label: 'LUA helper libraries',
      items: [
        {type: 'autogenerated', dirName: 'libs'},
      ],
    },
    {
      type: 'category',
      label: 'Enterprise functionality',
      items: [
        {type: 'doc', id: 'appnotes/databanking', label: 'Databanking and multi-station rework'},
        {
          type: 'category',
          label: 'Central user administration',
          link: {type: 'doc', id: 'appnotes/userdb'},
          items: [
            {type: 'doc', id: 'appnotes/userdb', label: 'Overview'},
            {type: 'doc', id: 'appnotes/userdb-heusermanager', label: 'heUserManager'},
            {type: 'doc', id: 'appnotes/userdb-activedirectory', label: 'Active Directory'},
          ],
        },
        {type: 'doc', id: 'appnotes/toolgateway', label: 'Tool roaming and dynamic parameters'},
        {type: 'doc', id: 'appnotes/traceability', label: 'Traceability'},
      ],
    },
    {
      type: 'category',
      label: 'Application notes',
      items: [
        {type: 'doc', id: 'appnotes/gui-layout-runtime', label: 'OGS runtime screen layout'},
        {type: 'doc', id: 'appnotes/debugging', label: 'Debugging LUA Scripts'},
        {type: 'doc', id: 'appnotes/station_io', label: 'Station IO'},
        {type: 'doc', id: 'appnotes/firebird-security', label: 'Firebird SQL configuration'},
        {type: 'doc', id: 'appnotes/branding', label: 'Branding'},
        {
          type: 'category',
          label: 'Using BLE Gateways',
          items: [
            {type: 'doc', id: 'appnotes/blegateway-openmqttgateway', label: 'OpenMQTT-Gateway'},
            {type: 'doc', id: 'appnotes/blegateway-minew-mg6', label: 'Minew MG6 Gateway'},
          ],
        },
      ],
    },
  ],
};

export default sidebars;
