// Sidebars scaffold — generated from MkDocs migration skill.
// Maps mkdocs.yml nav tree to Docusaurus sidebar structure.
//
// MIGRATE: Replace this with your actual nav hierarchy from mkdocs.yml.
//
// MkDocs nav example:
//   nav:
//     - Home: index.md
//     - Getting Started:
//       - Installation: getting-started/installation.md
//       - Configuration: getting-started/configuration.md
//     - User Guide:
//       - Overview: guide/overview.md
//       - Features: guide/features.md
//     - API Reference: api/  # auto-discover
//
// Becomes the sidebar below:

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    // MIGRATE: nav leaf → doc ID (file path without .md extension)
    'index',

    // MIGRATE: nav section → category
    {
      type: 'category',
      label: 'Getting Started',    // MIGRATE: section label from nav
      collapsed: false,
      items: [
        'getting-started/installation',   // MIGRATE: nav leaf path
        'getting-started/configuration',
      ],
    },

    {
      type: 'category',
      label: 'User Guide',
      collapsed: true,
      // Option A: Explicit items (mirrors nav entries)
      items: [
        'guide/overview',
        'guide/features',
      ],
      // Option B: If MkDocs had no explicit nav for this section,
      // use autogenerated sidebar instead:
      // items: [{ type: 'autogenerated', dirName: 'guide' }],
    },

    // MIGRATE: Sections with no explicit nav → autogenerated
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'generated-index' },  // Auto-generates an index page
      items: [
        { type: 'autogenerated', dirName: 'api' },
      ],
    },
  ],
};

export default sidebars;
